language: python

install: pip install -r requirements.txt

script: scripts/travis-build.sh
branches:
  only:
  - gh-pages
  - /.*/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  name: Robot Fairhurst
  keep-history: true
  on:
    branch: gh-pages
    condition: "-f .deploy"
